#docker-compose.yml
version: '3'

services:
  0xy_healthcare_data_analysis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    depends_on: #note, only ensures the order of service startup, not fully initialised, implement if any issues, when Flask app trys to connect to MongoDB before it's ready
      - mongo
      
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"