#docker-compose.yml

version: '3'

services:
  0xy_healthcare_data_analysis:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    depends_on:
      - mongo
      
  mongo:
  image: mongo:latest
  ports:
  - "27017:27017"