name: CI/CD Pipeline

# every push or pull request to the main branch, the pipeline will run.
on:
  push:
    branches: [ main, branch1, branch2 ]
  pull_request:
    branches: [ main, branch1, branch2 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.16

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
